/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.workshopjdbc3a48.services;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import edu.workshopjdbc3a48.entities.Produit;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.Date;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

/**
 *
 * @author Dhia werteteni
 */
public class Pdf {

    public static double TotaleCommande = 0;
    public static ObservableList<Produit> listpanier = FXCollections.observableArrayList();

    private static String FILE = "C:\\test\\Order.pdf";

    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

//*********************************************************************************************
    //********************  MAIN ********************************************
    public static void main(String[] args) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            addTitlePage(document);
            Desktop.getDesktop().open(new File("C:\\test\\Order.pdf"));
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //********************************* END MAIN **********************************************  
    //********************************************************************************************   
    private static void addTitlePage(Document document)
            throws DocumentException, BadElementException, IOException {
        ServiceCommande c = new ServiceCommande();

        Paragraph preface = new Paragraph();
        addEmptyLine(preface, 1);
        Paragraph paragraph = new Paragraph("Your Order ", catFont);
        paragraph.setAlignment(Element.ALIGN_CENTER);
        preface.add(paragraph);
        addEmptyLine(preface, 3);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Thanks ", smallBold));
         preface.add(new Paragraph(
                "  you purchased from our products in  " + new Date(), smallBold));
         
        addEmptyLine(preface, 1);
        preface.add(new Paragraph(
                "This is you Total",
                smallBold));
        //****************************************************************************************************

        

        // table.setHeaderRows(1);
        addEmptyLine(preface, 2);
        Paragraph preface2 = new Paragraph();
        preface2.add(new Paragraph(
                "Total to pay : " + TotaleCommande,
                redFont));
        preface2.setAlignment(Element.ALIGN_RIGHT);
        preface2.setIndentationLeft(300);
        Image img;
        //img = Image.getInstance("C:\\Users\\mariem\\Documents\\NetBeansProjects\\gestionshopp\\src\\images\\logo.jpg");
        //img.setAlignment(Element.ALIGN_CENTER);
        //    document.add(img);
        addEmptyLine(preface, 1);

        document.add(preface);
        document.add(preface2);
        // Start a new page
        // document.newPage();
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

    public void createpdf() throws FileNotFoundException, IOException {
        try {

            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            addTitlePage(document);
            Desktop.getDesktop().open(new File("C:\\test\\Order.pdf"));
            document.close();
        } catch (DocumentException e) {
        }
    }

}
